[setup]
python310 = true
gcc = true

[install]
command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
command = "gunicorn ppdb-app.wsgi:application"
