# Generated by Django 4.2.5 on 2023-09-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=300)),
                ('nik', models.CharField(max_length=16)),
                ('nokk', models.CharField(blank=True, max_length=16, null=True)),
                ('nisn', models.CharField(max_length=10)),
                ('tempat_lahir', models.CharField(blank=True, max_length=400, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('asal_sekolah', models.CharField(blank=True, max_length=400, null=True)),
                ('asal_kabupaten', models.CharField(blank=True, max_length=400, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
