# Generated by Django 4.2.5 on 2023-09-30 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='nik',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(limit_value=16), django.core.validators.MaxLengthValidator(limit_value=16)]),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='nisn',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='nokk',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=16), django.core.validators.MaxLengthValidator(limit_value=16)]),
        ),
    ]
