# Generated by Django 4.2.5 on 2023-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_datasiswa_nik_alter_datasiswa_nisn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasiswa',
            name='noPendaftaran',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
