# Generated by Django 4.2.5 on 2023-10-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_datasiswa_nopendaftaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='alamat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
