# Generated by Django 4.2.5 on 2023-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_datasiswa_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahun'),
        ),
    ]
