# Generated by Django 4.2.5 on 2023-10-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_rekap', models.DateField()),
                ('total_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.datasiswa')),
            ],
        ),
        migrations.DeleteModel(
            name='Pembayaran',
        ),
    ]
