# Generated by Django 4.2.5 on 2023-10-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rekappembayaran_delete_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(unique=True)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='namaAyah',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='namaIbu',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='nikAyah',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='nikIbu',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='noKip',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='noPkh',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='pekerjaanAyah',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='pekerjaanIbu',
        ),
        migrations.RemoveField(
            model_name='datasiswa',
            name='tahun',
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='tahun_pendaftaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pengaturan'),
        ),
    ]
