# Generated by Django 4.2.5 on 2023-10-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pengaturan_remove_datasiswa_namaayah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasiswa',
            name='tahun_pendaftaran',
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='namaAyah',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='namaIbu',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='nikAyah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='nikIbu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='noKip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='noPkh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='pekerjaanAyah',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='pekerjaanIbu',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datasiswa',
            name='tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahun'),
        ),
        migrations.DeleteModel(
            name='Pengaturan',
        ),
    ]
