# Generated by Django 4.2.5 on 2023-10-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_datasiswa_tahun_pendaftaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='tahun',
            field=models.IntegerField(default=2023, null=True, verbose_name='Tahun'),
        ),
    ]
