# Generated by Django 4.2.5 on 2023-10-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_datasiswa_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasiswa',
            name='tahun',
        ),
    ]
