# Generated by Django 4.2.5 on 2023-10-09 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_datasiswa_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasiswa',
            name='tahun',
            field=models.DateField(auto_created=True, default=datetime.datetime(2023, 10, 9, 14, 18, 12, 780010, tzinfo=datetime.timezone.utc)),
        ),
    ]
