# Generated by Django 4.2.5 on 2023-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_datasiswa_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekappembayaran',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasiswa',
            name='tahun',
            field=models.IntegerField(auto_created=True, verbose_name='Tahun'),
        ),
    ]
