# Generated by Django 4.2.5 on 2023-11-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_pengaturan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturan',
            name='total_pembayaran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
